export const ValidationMessage = {
  Empty: "Please fill the field",
  Alpha: "Please type alphabets only",
  Numbers: "Please type numbers only",
  StringLimit: "Please Don't exceed limit",
  WrongPassword: "Wrong Password Please type again",
  RegexPassword:
    "Password  must be between 6 to 20 which contains at least one numeric digit,one uppercase and one lowercase letter",
  RegexEmail: "Please enter valid email",
  RequiredEmail: "Please enter Email",
  RequiredPassword: "Please enter Password",
  RequiredName: "Please enter ",
  ValidCharacters: "Please enter Valid Characters",
  ConfirmPassword: "Please enter correct Password",
  Login: "Invalid Email and Password",
  Area: "Please select Shop Area",
  Vendor_Category: "Please select Shop Category",
  Pincode: "Please enter only 6 numbers",
  Mobile: "Please enter 10 numbers",
  TimeErrorOpen: "Please enter correct Opening time",
  TimeErrorClose: "Please enter correct Closing time",
};
